name: Upload Onbid CSV to Snowflake

on:
  push:
    paths:
      - 'data/*.csv'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Snowflake Connector
      run: pip install snowflake-connector-python

    - name: Upload to Snowflake
      env:
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_STAGE: ${{ secrets.SNOWFLAKE_STAGE }}
      run: |
        python <<EOF
        import os, glob
        import snowflake.connector

        conn = snowflake.connector.connect(
            user=os.environ['SNOWFLAKE_USER'],
            password=os.environ['SNOWFLAKE_PASSWORD'],
            account=os.environ['SNOWFLAKE_ACCOUNT'],
            warehouse=os.environ['SNOWFLAKE_WAREHOUSE'],
            database=os.environ['SNOWFLAKE_DATABASE'],
            schema=os.environ['SNOWFLAKE_SCHEMA']
        )
        cur = conn.cursor()
        files = glob.glob("data/*.csv")

        for file in files:
            file_path = os.path.abspath(file)
            file_name = os.path.basename(file)

            cur.execute(f"PUT file://{file_path} {os.environ['SNOWFLAKE_STAGE']} OVERWRITE=TRUE")

            cur.execute(f"""
                COPY INTO onbid_results
                FROM {os.environ['SNOWFLAKE_STAGE']}/{file_name}
                FILE_FORMAT = (FORMAT_NAME = 'korean_csv_format')
            """)
            
        print("== ENVIRONMENT DEBUG ==")
        for key in ["SNOWFLAKE_ACCOUNT", "SNOWFLAKE_USER", "SNOWFLAKE_DATABASE"]:
          print(key, "=", repr(os.environ.get(key)))

        cur.close()
        conn.close()
        EOF
